# Generated by Django 4.1.7 on 2023-03-03 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Caregoria",
            new_name="Categoria",
        ),
    ]
